Module migration from old utils to new SDK
Clarifai/module-gallery pull request #18
Opened 2023-09-26 15:56 UTC by mogith-pn

https://clarifai.atlassian.net/browse/TT-2958

2023-10-06 11:47 UTC, sanjaychelliah reviewed
Some comments..

2023-10-06 11:47 UTC, sanjaychelliah commented on pages/grid.py
> +from clarifai.client.auth import create_stub
This import is not needed..

2023-10-06 11:47 UTC, sanjaychelliah commented on pages/mosaic.py
> +from clarifai.client.auth import create_stub
Both `service_pb2` and `create_stub `  are not needed here..

2023-10-06 11:47 UTC, sanjaychelliah commented on pages/mosaic.py
>  metadata = auth.metadata
`metadata` variable is not used anywhere in this script.

2023-10-06 11:47 UTC, sanjaychelliah commented on utils/api_utils.py
`predict_from_image` and `predict_from_text` can be directly used from the SDK in all the scripts..

2023-10-10 12:23 UTC, sanjaychelliah requested changes
Create stub import `from clarifai.client.auth import create_stub ` is not needed in any script except in `api_utils.py`

2023-10-10 12:23 UTC, sanjaychelliah commented on pages/ner.py
>  model_version_id = 'a813ff5b362c41f790c506b871e7dea4'
Can we directly use something like this `model_prediction = Model("https://clarifai.com/anthropic/completion/models/claude-v2").predict_by_bytes(b"Write a tweet on future of AI", "text")`

2023-10-10 13:49 UTC, mogith-pn commented
> Create stub import `from clarifai.client.auth import create_stub ` is not needed in any script except in `api_utils.py`

Hi Sanjay,
We are using `UserDataObject` as arguments in functions inside grid.py, metrics.py, mosaic.py as well. I have removed it from compare.py and from ner.py

2023-10-11 07:44 UTC, sanjaychelliah approved these changes
LGTM.

2023-10-11 08:42 UTC, merged